### ISSUE TITLE
Для этого есть Makefile

### ISSUE THREAD

**Issue by ahvastunov-itmo** [Killaz/2017-C-BMP-Monochrome#1]
https://github.com/Killaz/2017-C-BMP-Monochrome/blob/00c249a83fbbc7495d68a28ad70898122f9968d3/build.bat#L2

**Comment by kanootoko** [comment]
Разбил один bat-файл с параметрами на два без параметров, если это имелось в виду. Они, как и раньше, передают DEBUG, равный единице или нулю в дефайны cmake.

**Comment by ahvastunov-itmo** [comment]
Тоже самое можно решить с помощью Makefile

**Comment by kanootoko** [comment]
Немного поменял CMakeLists, до этого он, вроде, вообще не компилировал, пока не получал информации о том, включен дебаг, или нет. А сейчас использует последнее значение.
