### ISSUE TITLE
Разбить на  маленькие функции

### ISSUE THREAD

**Issue by ahvastunov-itmo** [Killaz/2017-C-BMP-Monochrome#3]
https://github.com/Killaz/2017-C-BMP-Monochrome/blob/00c249a83fbbc7495d68a28ad70898122f9968d3/bmp.c#L231

**Comment by kanootoko** [comment]
Разбил. Тексты функций вывода 1-битной и 2/4-битной BMP довольно сильно похожи, но суть у них разная, так что думаю, это приемлемо.
