### ISSUE TITLE
Для этого более поще написать функицию log в которую завернуть ifdef вместо того что бы писать его везде

### ISSUE THREAD

**Issue by ahvastunov-itmo** [Killaz/2017-C-BMP-Monochrome#4]
https://github.com/Killaz/2017-C-BMP-Monochrome/blob/00c249a83fbbc7495d68a28ad70898122f9968d3/BMP_to_monochrome.c#L52

**Comment by kanootoko** [comment]
Избавился от #ifdef ECHO_ON в коде main'а путем добавления isEchoOn(). Это, что имелось в виду?

**Comment by ahvastunov-itmo** [comment]
Нет, добавить функцию log( ) {   #ifdef ECHO_ON print #endif }

**Comment by kanootoko** [comment]
Создал соответствующую функцию Log, оборачивающую printf(). Теперь это то, что предполагалось?
